spring:
  datasource:
    username: root
    password: "010712"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.25.67:3306/ucs
  web:
    resources:
      static-locations: classpath:/templates
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/templates/, classpath:/public/,classpath:/resources/static/images/
  gson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size=10MB
      max-request-size=10MB
    enabled: true

server:
  port: 9088
  servlet:
    session:
      timeout: 180m

mybatis:
  configuration:
    call-setters-on-nulls: true
