spring:
  datasource:
    username: root
    password: "010712"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ucs
  web:
    resources:
      static-locations: classpath:/templates
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/templates/, classpath:/public/,classpath:/resources/static/images/
  gson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size=10MB
      max-request-size=10MB
    enabled: true

server:
  port: 9088
  servlet:
    session:
      timeout: 180m

mybatis:
  configuration:
    call-setters-on-nulls: true

shiro-readis:
  enabled: true
  redis-mapper:
    host: 127.0.0.1:6379

gbo601:
  jwt:
    #加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #有效期七天,秒为单位
    expire: 604800
    header: Authorization
